version: '3.8'
services:
  postgres:
    image: postgres:latest
    volumes:
      - "postgres:/var/lib/postgresql/data"
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    deploy:
      restart_policy:
        condition: any

  compounds-migrate:
    build:
      context: .
      target: migrate
    depends_on:
      - postgres
    environment:
      - PORT=4000
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASS=postgres

  compounds:
    build:
      context: .
      target: release
    ports:
      - 6000:4000
    depends_on:
      - postgres
      - compounds-migrate
    environment:
      - PORT=4000
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASS=postgres

volumes:
  postgres: