version: "3.8"
services:
  postgres:
    image: postgres:latest
    volumes:
      - "postgres:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres

    ports:
      - 5432:5432
    deploy:
      restart_policy:
        condition: any

  compounds:
    build:
      context: .
      target: prod
      args:
        SECRET_KEY_BASE: DeX0btDDaqwsqyAeQKBvsOyy9ckcrjaVq0JsRcYOR7Wrgyv0WRNekaK9CQ1bKZUv
    ports:
      - 4000:4000
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASS: postgres

volumes:
  postgres:
